ISM_Project/Controllers/DIController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ISM_Project.Models;

namespace ISM_Project.Controllers
{
    /// <summary>
    /// DI - Controller - contains the functionality of Form35 , Notify ACCID and save and update of Aircraft details 
    /// </summary> 
    /// 
    public class DIController : Controller
    {
        MailConfiguration mail = new MailConfiguration();
        Common comm = new Common();
        static int InvestigationFileID = 0; static int OccurrenceId = 0; static int TabIndex = 0; static string NotificationId = string.Empty;
        PdfGeneration pdf = new PdfGeneration();
        gcaa_ismEntities dc = new gcaa_ismEntities();

        /// <summary>
        /// Convert date time value as string format
        /// </summary> 
        /// 
        /// <param name="dt">Receive the date time value from calendar .</param>
        public string convertDateTime(DateTime dt)
        {
            string conv_Time = string.Empty;
            if (dt != null)
                conv_Time = Convert.ToDateTime(dt).ToString("dd-MM-yyyy HH:mm");


            return conv_Time;
        }
        /// <summary>
        /// Fill DropDown Value And Default Data while page load 
        /// </summary> 
        /// 
        public void FillDroppedDownValueAndDefaultData()
        {
            #region Fill Master Data In ViewBag that is used to fill dropped down in view page of form35

            try
            {
                var country_id = dc.LKCountries.ToList().OrderBy(x => x.LKCountryName);
                SelectList countryid = new SelectList(country_id, "LKCountryID", "LKCountryName");
                ViewBag.country_id = countryid;

                var airport_id = dc.LKAirports.ToList().OrderBy(x => x.LKAirportName);
                SelectList airportid = new SelectList(airport_id, "LKAirportID", "LKAirportName");
                ViewBag.airport_id = airportid;

                var makes = dc.LKAircraftMakes.ToList().OrderBy(x => x.LKAircraftMakeName);
                SelectList makelist = new SelectList(makes, "LKAircraftMakeID", "LKAircraftMakeName");
                ViewBag.makes = makelist;

                var aircraft_type = dc.LKAircraftTypes.ToList().OrderBy(x => x.LKAircraftTypeName);
                SelectList aircrafttype = new SelectList(aircraft_type, "LKAircraftTypeID", "LKAircraftTypeName");
                ViewBag.aircraft_type = aircrafttype;

                var airline_operator = dc.LKAirlineOperators.ToList().OrderBy(x => x.LKAirlineOperatorName);
                SelectList airlineoperator = new SelectList(airline_operator, "LKAirlineOperatorID", "LKAirlineOperatorName");
                ViewBag.airline_operator = airlineoperator;

                var Category_id = dc.LKAircraftCategories.ToList().OrderBy(x => x.LKAircraftCategoryName);
                SelectList Category = new SelectList(Category_id, "LKAircraftCategoryId", "LKAircraftCategoryName");
                ViewBag.Category_id = Category;

                var common_OccurenceClassification = dc.USP_GET_INCIDENTTYPE().OrderBy(x => x.LKIncidentTypeID);
                SelectList OccurenceClassification = new SelectList(common_OccurenceClassification, "LKIncidentTypeID", "LKIncidentTypeName");
                ViewBag.common_OccurenceClassification = common_OccurenceClassification;

                var Accident_Incident = dc.USP_GET_MASTERVALUES(1); //10
                SelectList AccidentIncident = new SelectList(Accident_Incident, "ID", "LKVALUE");
                ViewBag.Accident_Incident = Accident_Incident;

                var largeaircraft_smallaircraft = dc.USP_GET_MASTERVALUES(2); // 11
                SelectList largeaircraftsmallaircraft = new SelectList(largeaircraft_smallaircraft, "ID", "LKVALUE");
                ViewBag.largeaircraft_smallaircraft = largeaircraft_smallaircraft;

                var Commercial_Private = dc.USP_GET_MASTERVALUES(3); //12
                SelectList CommercialPrivate = new SelectList(Commercial_Private, "ID", "LKVALUE");
                ViewBag.Commercial_Private = Commercial_Private;

                var UAEregisteredaircraft_UAEoperator = dc.USP_GET_MASTERVALUES(4); //13
                SelectList UAEregisteredaircraftUAEoperator = new SelectList(UAEregisteredaircraft_UAEoperator, "ID", "LKVALUE");
                ViewBag.UAEregisteredaircraft_UAEoperator = UAEregisteredaircraft_UAEoperator;

                var DI_Suggestion = dc.USP_GET_MASTERVALUES(5);
                SelectList DISuggestion = new SelectList(DI_Suggestion, "ID", "LKVALUE");
                ViewBag.DI_Suggestion = DI_Suggestion;

                var DI_FurtherSuggestion = dc.USP_GET_MASTERVALUES(6);
                SelectList DIFurtherSuggestion = new SelectList(DI_FurtherSuggestion, "ID", "LKVALUE");
                ViewBag.DI_FurtherSuggestion = DI_FurtherSuggestion;

                var Investigation_Type = dc.USP_GET_MASTERVALUES(7);
                SelectList InvestigationType = new SelectList(Investigation_Type, "ID", "LKVALUE");
                ViewBag.Investigation_Type = Investigation_Type;

                var Yes_No1 = dc.USP_GET_MASTERVALUES(17);
                SelectList YesNo = new SelectList(Yes_No1, "ID", "LKVALUE");
                ViewBag.Yes_No_1 = Yes_No1;

                var Yes_No2 = dc.USP_GET_MASTERVALUES(17);
                SelectList YesNo2 = new SelectList(Yes_No2, "ID", "LKVALUE");
                ViewBag.Yes_No_2 = Yes_No2;

                var Yes_No3 = dc.USP_GET_MASTERVALUES(17);
                SelectList YesNo3 = new SelectList(Yes_No3, "ID", "LKVALUE");
                ViewBag.Yes_No_3 = Yes_No3;

                var Yes_No4 = dc.USP_GET_MASTERVALUES(17);
                SelectList YesNo4 = new SelectList(Yes_No4, "ID", "LKVALUE");
                ViewBag.Yes_No_4 = Yes_No4;

                var Yes_No5 = dc.USP_GET_MASTERVALUES(17);
                SelectList YesNo5 = new SelectList(Yes_No5, "ID", "LKVALUE");
                ViewBag.Yes_No_5 = Yes_No5;

                var Yes_No6 = dc.USP_GET_MASTERVALUES(17);
                SelectList YesNo6 = new SelectList(Yes_No6, "ID", "LKVALUE");
                ViewBag.Yes_No_6 = Yes_No6;

                var Yes_No7 = dc.USP_GET_MASTERVALUES(17);
                SelectList YesNo7 = new SelectList(Yes_No7, "ID", "LKVALUE");
                ViewBag.Yes_No_7 = Yes_No7;

                var Yes_No8 = dc.USP_GET_MASTERVALUES(17);
                SelectList YesNo8 = new SelectList(Yes_No8, "ID", "LKVALUE");
                ViewBag.Yes_No_8 = Yes_No8;

                var Attach_Files = dc.USP_VIEW_INVESTIGATION_ATTACHMENTFILE(InvestigationFileID);
                SelectList AttachFiles = new SelectList(Attach_Files, "InvestigationDocumentAsAttachmentID", "AttachmentPublicUrl");
                ViewBag.Attach_Files = Attach_Files;

                var AircraftModel_id = dc.LKAircraftModels.ToList().OrderBy(x => x.LKAircraftModelName);
                SelectList AircraftModelId = new SelectList(AircraftModel_id, "LKAircraftModelId", "LKAircraftModelName");
                ViewBag.AircraftModel_Id = AircraftModelId;

                ViewBag.TimeGapInDays = string.Empty;

                ViewBag.TimeGapInHours = string.Empty;

                var Registration_id = dc.LKAircraftRegistrations.ToList().OrderBy(x => x.LKAircraftRegistrationName);
                SelectList Registrationid = new SelectList(Registration_id, "LKAircraftRegistrationID", "LKAircraftRegistrationName");
                ViewBag.Registration_id = Registrationid;

                var UAEoperator = dc.USP_GET_MASTERVALUES(22); //14
                SelectList UAE_operator = new SelectList(UAEoperator, "ID", "LKVALUE");
                ViewBag.UAE_operatorvalue = UAEoperator;

                var Occurrence_Categorization = dc.LKOccurrenceCategorizations.ToList().OrderBy(x => x.LKOccurrenceCategorizationId);
                SelectList OccurCategorization = new SelectList(Occurrence_Categorization, "LKOccurrenceCategorizationId", "OccurrenceCategorization");
                ViewBag.Occur_Categorization = OccurCategorization;
            }
            catch (System.Exception ex)
            {
                comm.Exception_Log("DIController", "FillDroppedDownValueAndDefaultData", "Message : " + ex.Message + "InnerException : " + ex.InnerException + " Line No : " + ex.StackTrace, Convert.ToInt32(Session["UserId"]));
            }

            #endregion
        }
        /// <summary>
        /// page redirect to Form35 view page with saved data
        /// </summary> 
        /// 
        /// <param name="id">Receive the investigation file id .</param>
        /// <param name="F35_status">Receive the status of investigation .</param>
        public ActionResult Form_35_Tab(int id = 0, string F35_status = "")
        {
            InvestigationModel _investigationMdl = new InvestigationModel();

            try
            {
                if (Session != null)
                {
                    if (Convert.ToInt32(Session["RoleId"]) == 2)
                    {
                        var CheckCaseInfo = dc.OccurrenceDetails.AsEnumerable().Where(a => a.CreatedBy == Convert.ToInt32(Session["Userid"]) &&

                                            a.OccurrenceDetailID == id).FirstOrDefault();

                        if (CheckCaseInfo != null)
                        {
                            if (F35_status == "Success")
                            {
                                ViewBag.F35_status = F35_status;
                            }
                            else if (F35_status == "F35_SubmitSuccess")
                            {
                                ViewBag.F35_SubmitSuccess = F35_status;
                            }

                            F35_status = "";

                            FillDroppedDownValueAndDefaultData();

ISM_Project/Views/DI/AddAirOperatorName.cshtml
@model ISM_Project.Models.LKAirlineOperator
@{
    ViewBag.Title = "AddAirOperatorName";
    // Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <div class="modal-title">
        <h2>Add Airline Operator</h2>
    </div>
</div>

<div class="modal-body" id="Airline_Operator">
    <small id="emailHelp" class="form-text popup_danger"></small>
    @using (Html.BeginForm("AddAirOperatorName", "DI", FormMethod.Post, new { id = "frm_AddAirOperatorName" }))
    {
        <div class="closeinvestigation-wrapp">
            <div class="closeinvestigation-inner create-user-table">
                <form>
                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            Airline Operator Name <span class="text-danger">*</span>
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @Html.TextBoxFor(m => m.LKAirlineOperatorName, new { @type = "text", @class = "form-control", @style = "margin-bottom:10px" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            Airline Operator Description <span class="text-danger"></span>
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @Html.TextAreaFor(m => m.LKAirlineOperatorDescription, new { @type = "text", @class = "form-control" })
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="modal-footer">            
            <button type="button" class="btn btn-save" onclick="SaveAirlineOperatorName()">Save</button>
        </div>
    }
</div>

ISM_Project/Views/DI/AddAircraftRegistration.cshtml
@model ISM_Project.Models.AircraftRegistration
@{
    ViewBag.Title = "AddAircraftRegistration";
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <div class="modal-title">
        <h2>Aircraft Details</h2>
    </div>
</div>

<div class="modal-body" id="Aircraft_Registration">
    <small id="emailHelp" class="form-text popup_danger"></small>
    @using (Html.BeginForm("AddAircraftRegistrations", "DI", FormMethod.Post, new { id = "frm_NewAircraftRegistration" }))
    {
        <div class="closeinvestigation-wrapp">
            <div class="closeinvestigation-inner create-user-table">
                <form>
                    <input type="hidden" id="aircid" value="0" />
                    @Html.HiddenFor(m => m.LKAircraftRegistrationID, new { @type = "text", @class = "form-control hidden" })

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            Aircraft Registration <span class="text-danger">*</span>
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @*@if (Model.LKAircraftRegistrationID > 0)
                                {
                                    @Html.TextBoxFor(m => m.LKAircraftRegistrationName, new { @type = "text", @class = "form-control", @style = "margin-bottom:10px", @readonly = "readonly" })
                                }
                                else
                                {*@
                            @Html.TextBoxFor(m => m.LKAircraftRegistrationName, new { @type = "text", @class = "form-control", @style = "margin-bottom:10px" })
                            @*}*@
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            Make and Model  <span class="text-danger"></span>
                        </label>
                        <div class="col-sm-8 col-form-box">

                            @if (Model.LKAircraftRegistrationID > 0)
                            {
                                @Html.TextBox("LKAircraftModelName", Model.LKAircraftModelName, new { @placeholder = "Start typing for suggestions", id = "LKAircraftModelName", @class = "ModelName form-control" })
                                @Html.Hidden("LKAircraftModelID", Model.LKAircraftModelID, new { id = "LKAircraftModelID", @class = "form-control" })
                            }
                            else
                            {
                                @Html.TextBox("LKAircraftModelName", null, new { @placeholder = "Start typing for suggestions", id = "LKAircraftModelName", @class = "ModelName form-control" })
                                @Html.Hidden("LKAircraftModelID", null, new { id = "LKAircraftModelID", @class = "form-control" })
                            }

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            Maximum Take Off Mass (kg) <span class="text-danger"></span>
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @Html.TextBoxFor(m => m.MaximumMass, new { @type = "text", @class = "form-control", @style = "margin-bottom:10px" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            Operator Name  <span class="text-danger">*</span>
                        </label>
                        <div class="col-sm-8 col-form-box">

                            @if (Model.LKAircraftRegistrationID > 0)
                            {
                                @Html.TextBox("LKAirlineOperatorName", Model.LKAirlineOperatorName, new { @placeholder = "Start typing for suggestions", id = "LKAirlineOperatorName", @class = "OperatorName form-control" })
                                @Html.Hidden("LKAirlineOperatorID", Model.LKAirlineOperatorID, new { id = "LKAirlineOperatorID", @class = "form-control" })
                            }
                            else
                            {
                                @Html.TextBox("LKAirlineOperatorName", null, new { @placeholder = "Start typing for suggestions", id = "LKAirlineOperatorName", @class = "OperatorName form-control" })
                                @Html.Hidden("LKAirlineOperatorID", null, new { id = "LKAirlineOperatorID", @class = "form-control" })
                            }

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            MSN <span class="text-danger"></span>
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @Html.TextBoxFor(m => m.MSN, new { @type = "text", @class = "form-control", @style = "margin-bottom:10px" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            Engine Info <span class="text-danger"></span>
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @Html.TextBoxFor(m => m.EngineInfo, new { @type = "text", @class = "form-control", @style = "margin-bottom:10px" })
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            State of Registry <span class="text-danger"></span>
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @*@Html.TextBoxFor(m => m.StateofRegistry, new { @type = "text", @class = "form-control", @style = "margin-bottom:10px" })*@

                            @Html.DropDownListFor(m => m.StateofRegistryID, ViewBag.State_Of_Registry as SelectList, "Select", new { @class = "form-control" })

                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            Aircraft Category <span class="text-danger"></span>
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @if (Model.LKAircraftRegistrationID > 0)
                            {
                                @Html.TextBox("LKAircraftCategoryName", Model.LKAircraftCategoryName, new { @placeholder = "Start typing for suggestions", id = "LKAircraftCategoryName", @class = "CategoryName form-control" })
                                @Html.Hidden("LKAircraftCategoryID", Model.LKAircraftCategoryID, new { id = "LKAircraftCategoryID", @class = "form-control" })
                            }
                            else
                            {
                                @Html.TextBox("LKAircraftCategoryName", null, new { @placeholder = "Start typing for suggestions", id = "LKAircraftCategoryName", @class = "CategoryName form-control" })
                                @Html.Hidden("LKAircraftCategoryID", null, new { id = "LKAircraftCategoryID", @class = "form-control" })
                            }
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            State of Operator <span class="text-danger"></span>
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @*@Html.TextBoxFor(m => m.StateofOperator, new { @type = "text", @class = "form-control", @style = "margin-bottom:10px" })*@

                            @Html.DropDownListFor(m => m.StateofOperatorID, ViewBag.State_Of_Operator as SelectList, "Select", new { @class = "form-control" })

                        </div>
                    </div>

                    @*<div class="form-group">
                            <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                                Operator Contact <span class="text-danger"></span>
                            </label>
                            <div class="col-sm-8 col-form-box">
                                @Html.TextBoxFor(m => m.OperatorContacts, new { @type = "text", @class = "form-control", @style = "margin-bottom:10px" })
                            </div>
                        </div>*@


                </form>
            </div>
        </div>
        <div class="modal-footer">
            @if (Model.LKAircraftRegistrationID == 0)
            {
                <button type="button" class="btn btn-save" onclick="SaveAircraftRegistration()">Save</button>
            }
            else
            {
                <button type="button" class="btn btn-save" onclick="SaveAircraftRegistration()">Update</button>
            }
        </div>
    }
</div>

ISM_Project/Views/DI/ChangeIncidentType.cshtml
@model ISM_Project.Models.InvestigationModel
@{
    ViewBag.Title = "ChangeIncidentType";
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = null;
}

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <div class="modal-title">
        <h2>Change Incident Type</h2>
    </div>
</div>

<div class="modal-body" id="Change_IncidentType">
    <small id="emailHelp" class="form-text popup_danger"></small>
    @using (Html.BeginForm("ChangeIncidentTypeSave", "DI", FormMethod.Post))
    {
    <div class="closeinvestigation-wrapp">
        <div class="closeinvestigation-inner create-user-table">
            <form>
                @Html.HiddenFor(m => m.InvestigationFileID, new { @class = "form-control hidden" })
                <input type="hidden" id="Inciden_id" value="0" />
                <div class="form-group ">
                    <div class="col-sm-8 col-form-box">
                        <div class="col-sm-8 col-form-box" id="radDISug">

                            @foreach (ISM_Project.Models.USP_GET_INCIDENTTYPE_Result Incident in ViewBag.Incident_TypeList)
                            {
                                <label class="radio">
                                    @Html.RadioButtonFor(m => m.LKIncidentTypeID, Incident.LKIncidentTypeID)

                                    @Html.Label(Incident.LKIncidentTypeName)
                                </label>
                            }
                            <br />
                        </div>
                    </div>
                </div>
            </form>
        </div>
        @if (Model.LKIncidentTypeID == 11)
        {
            <div class="form-group" id="hideoccurclassification">
                <label class="col-sm-4 col-form-label" for="exampleInputPassword1"><span class="text-danger"></span></label>
                <div class="col-sm-12 col-form-box event-desc">
                    @Html.TextAreaFor(m => m.OtherOccurClassification, new { @placeholder = "Enter occurrence details", @type = "text", @class = "form-control", @style = "height: inherit" })
                </div>
            </div>
        }
        else
        {
            <div class="form-group" id="hideoccurclassification" hidden ="hidden">
                <label class="col-sm-4 col-form-label" for="exampleInputPassword1"><span class="text-danger"></span></label>
                <div class="col-sm-12 col-form-box event-desc">
                    @Html.TextAreaFor(m => m.OtherOccurClassification, new { @placeholder = "", @type = "text", @class = "form-control", @style = "height: inherit" })
                </div>
            </div>
        }
    </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-save" onclick="UpdateIncidentType()">Save</button>
        </div>
    }
</div>