ISM_Project/Models/teammanagement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ISM_Project.Models
{
    public class teammanagement
    {


        public IEnumerable<USP_VIEW_ACCID_TEAM_MEMBERS_Result> accidteammembers { get; set; }
        public List<USP_VIEW_ASSIGN_TEAM_MEMBERS_Result> assignteammembers { get; set; }
        public string rem_reason { get; set; }
        public IEnumerable<USP_VIEW_INVESTIGATION_FORM35_Result> Inv_team { get; set; }
    }
}

ISM_Project/Controllers/TaskController.cs
using DocumentFormat.OpenXml.Wordprocessing;
using ISM_Project.Models;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using PagedList;
using System.Text.RegularExpressions;
using System.Reflection;
using System.Xml.Linq;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using A1 = DocumentFormat.OpenXml.Drawing;
using DW = DocumentFormat.OpenXml.Drawing.Wordprocessing;
using PIC = DocumentFormat.OpenXml.Drawing.Pictures;
using System.Drawing;

namespace ISM_Project.Controllers
{
    /// <summary>
    /// Task Controller - Contains all functionality of Investigation Team management, Scope definition,Task assignment,Evidence Management,Close Investigation
    /// </summary>  
    public class TaskController : Controller
    {
        gcaa_ismEntities dc = new gcaa_ismEntities();
        Common comm = new Common();
        string[] attachments = new string[50];
        MailConfiguration mail = new MailConfiguration();
        static int investigation_fileid = 0; static int InvestigationEvidenceMovementId = 0; static int InvestigationEvidenceId = 0;
        static string[] SharepointfilePath = new string[100]; static string[] SharepointAnonymousPath = new string[100];

        /// <summary>
        /// Listing the investigation task groups based on the particular investigation
        /// </summary>  
        /// <param name="id">Receive investigation file id</param>
        /// 
        public ActionResult Defn_Inv_Scope(int id = 0)
        {
            InvScope scop = new InvScope();

            try
            {
                if (Convert.ToInt32(Session["RoleId"]) == 4 || Convert.ToInt32(Session["RoleId"]) == 3 || Convert.ToInt32(Session["RoleId"]) == 6 || Convert.ToInt32(Session["RoleId"]) == 7)
                {
                    var CheckInvPermission = dc.InvestigationIICAssignments.AsEnumerable().Where(a => a.InvestigationFileID == id).FirstOrDefault();

                    if ((CheckInvPermission.IICAssigned == Convert.ToInt32(Session["UserId"]) &&

                                           CheckInvPermission.InvestigationFileID == id) || Convert.ToInt32(Session["RoleId"]) == 3 || Convert.ToInt32(Session["RoleId"]) == 6 || Convert.ToInt32(Session["RoleId"]) == 4 || Convert.ToInt32(Session["RoleId"]) == 7)
                    {
                        TempData["BackPage"] = "yes";
                        TempData["active_url_Defn_Inv_Scope"] = "tm";
                        TempData["active_url_Defn_Inv_Scope_iic"] = "iic";
                        TempData["lf_menu"] = "1";
                        TempData["active_url_manuals_iic"] = "not-iic";


                        var InvInfo = dc.USP_VIEW_INVESTIGATION_INVESTIGATIONID(id).FirstOrDefault();

                        if (InvInfo != null)
                        {
                            scop.InvestigationId = InvInfo.InvestigationFileID;

                            TempData["PageHead"] = InvInfo.InvestigationFileNumber;

                            Session["InvFileID"] = InvInfo.InvestigationFileID;

                            TempData["InvId"] = InvInfo.InvestigationFileID;
                            TempData["InvFileID"] = InvInfo.InvestigationFileID;

                            scop.LocalDateAndTimeOfOccurrence = InvInfo.LocalDateAndTimeOfOccurrence.ToString();

                            scop.UTCDateAndTimeOfOccurrence = InvInfo.UTCDateAndTimeOfOccurrence.ToString();

                            scop.NotifierName = InvInfo.NotifierName;

                            scop.NotifierOrganization = InvInfo.NotifierOrganization;

                            var Investigation_Scope = dc.USP_VIEW_INVESTIGATION_SCOPE_DEFINITION_INVESTIGATIONID(id).ToList();

                            if (Investigation_Scope.Count == 0 || Investigation_Scope == null)
                            {
                                var Inv_Scope = dc.USP_VIEW_INVESTIGATION_SCOPE_DEFINITION(id).ToList();

                                ViewBag.InvestigationScope = Inv_Scope;
                            }
                            else
                            {
                                ViewBag.InvestigationScope = Investigation_Scope;
                            }

                            TempData["id"] = id;

                            var invInfo = dc.USP_VIEW_INVESTIGATION_FORM35(id).FirstOrDefault();

                            TempData["INV_STATUS"] = invInfo.LKInvestigationStatusTypeID;
                        }
                        else
                        {
                            return RedirectToAction("PageNotFound", "Error");
                        }
                    }
                    else
                    {

                    }
                }
                else
                {
                    return RedirectToAction("Dashboard", "Home");
                }
            }
            catch (System.Exception ex)
            {
                comm.Exception_Log("TASKController", "Defn_Inv_Scope(int id = 0)", "Message : " + ex.Message + "InnerException : " + ex.InnerException + " Line No : " + ex.StackTrace, Convert.ToInt32(Session["UserId"]));

                return RedirectToAction("PageNotFound", "Error");
            }

            return View(scop);
        }
        /// <summary>
        /// Save the investigation task groups details based on the investigation
        /// </summary>        
        /// <param name="scope">Receive investigation scope identification details</param>
        [HttpPost]
        public ActionResult Defn_Inv_Scope(InvScope scope)
        {
            //var DbTransaction = dc.Database.BeginTransaction();

            try
            {
                if (Convert.ToInt32(Session["RoleId"]) == 4 || Convert.ToInt32(Session["RoleId"]) == 3 || Convert.ToInt32(Session["RoleId"]) == 7)
                {
                    var result = 0;

                    int TaskGroupInScope = 1; string[] StaticEvents = { "E1", "E2", "E64", "E65", "E66" };

                    for (int i = 0; i < scope.invScopeId.Length; i++)
                    {
                        if (Convert.ToInt32(scope.invScopeStatus[i]) == 2)
                        {
                            TaskGroupInScope = 0;

                            //// Check If Scope Already Define Or Not and If The corresponding Event get Started.

                            //if (Convert.ToInt32(scope.invScopeId[i]) > 0)
                            //{
                            //    var ScopeInfo = dc.InvestigationScopeDefinitions.AsEnumerable().Where(a => a.InvestigationFileID == scope.InvestigationId

                            //                    && a.InvestigationScopeDefinitionID == Convert.ToInt32(scope.invScopeId[i])).FirstOrDefault();

                            //    if (ScopeInfo != null)
                            //    {
                            //        if (ScopeInfo.InvestigationTaskGroupInScope == 1)
                            //        {
                            //            if (ScopeInfo.NumberOfSubEvents != ScopeInfo.NumberOfUnassignedEvents)
                            //            {
                            //                TaskGroupInScope = 1;
                            //            }
                            //        }
                            //    }
                            //}                                                        

                            if (Convert.ToInt32(scope.invScopeId[i]) > 0)
                            {
                                var ScopeInfo = dc.InvestigationScopeDefinitions.AsEnumerable().Where(a => a.InvestigationFileID == scope.InvestigationId

                                                && a.InvestigationScopeDefinitionID == Convert.ToInt32(scope.invScopeId[i])).FirstOrDefault();

                                if (ScopeInfo != null)
                                {
                                    if (ScopeInfo.InvestigationTaskGroupInScope == 1)
                                    {
                                        if (ScopeInfo.NumberOfSubEvents != ScopeInfo.NumberOfUnassignedEvents)
                                        {
                                            var CheckTaskDetail = dc.InvestigationTaskDetails.AsEnumerable().Where(a => a.InvestigationFileID == scope.InvestigationId

                                                                  && a.InvestigationTaskGroupID != ScopeInfo.InvestigationTaskGroupID).FirstOrDefault();

                                            if (CheckTaskDetail != null) // Update Scope Definition columns value set as Zero & Update Event Group Id
                                            {
                                                var CheckTaskAssign = dc.InvestigationTaskAssignments.AsEnumerable().Where(a => a.InvestigationFileID == scope.InvestigationId

                                                                  && a.InvestigationTaskGroupID == CheckTaskDetail.InvestigationTaskGroupID).FirstOrDefault();

                                                var TaskDetail = dc.InvestigationTaskDetails.AsEnumerable().Where(a => a.InvestigationFileID == scope.InvestigationId

                                                                  && a.InvestigationTaskGroupID == Convert.ToInt32(scope.invTaskGroupId[i])).ToList();

                                                var AssignDetail = dc.InvestigationTaskAssignments.AsEnumerable().Where(a => a.InvestigationFileID == scope.InvestigationId

                                                                  && a.InvestigationTaskGroupID == Convert.ToInt32(scope.invTaskGroupId[i])).ToList();

                                                if (TaskDetail != null)

ISM_Project/Views/Task/AddNewMovement.cshtml
@model ISM_Project.Models.InvEvidence
@{
    ViewBag.Title = "AddNewMovement";
    //Layout = "~/Views/Shared/_Layout.cshtml";
    Layout = null;
}

<!-- Add New Evidence Movement popup -->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <div class="modal-title">
        <h2>Evidence Movement</h2>
    </div>
</div>
<div class="modal-body" id="Movements_data">
    <small id="emailHelp" class="form-text popup_danger"></small>
    @using (Html.BeginForm("AddNewMovements", "Task", FormMethod.Post, new { id = "frm_Movement" }))
    {
        @Html.HiddenFor(m => m.InvestigationEvidenceID, new { @type = "text", @class = "form-control hidden" })
        @Html.HiddenFor(m => m.InvestigationEvidenceMovementID, new { @type = "text", @class = "form-control hidden" })
        @Html.HiddenFor(m => m.InvestigationFileID, new { @type = "text", @class = "form-control hidden" })

        <div class="closeinvestigation-wrapp">
            <div class="closeinvestigation-inner create-user-table">
                <form>

                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            Evidence Movement Type<span class="text-danger">*</span>
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @Html.DropDownListFor(m => m.EvidenceMovementType, ViewBag.Evidence_MovementType as SelectList, "Select", new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">

                        </label>
                        <div class="col-sm-8 col-form-box">

                            @if (Model.EvidenceReturned == 0)
                            {
                                <input type="checkbox" value="@Model.EvidenceReturned" name="EvidenceReturned" id="EvidenceReturned">
                                <span class="rt">Returned to Orginal Custodian</span>
                            }
                            else
                            {
                                <input type="checkbox" checked="checked" value="@Model.EvidenceReturned" name="EvidenceReturned" id="EvidenceReturned">
                                <span class="rt">Returned to Orginal Custodian</span>
                            }

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">Date of Movement<span class="text-danger">*</span></label>
                        <div class="col-sm-8 col-form-box">
                            <div type="date" class='input-group date_only_nofuture'>
                           
                                <input type="text" id="DateOfMovement" class="form-control" name="DateOfMovement" value="@ViewBag.DateOfMovement" />
                              
                                <span class="input-group-addon">
                                    <span class="fa fa-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">Evidence Received By<span class="text-danger">*</span></label>
                        <div class="col-sm-8 col-form-box">
                           
                            @Html.TextBoxFor(m => m.MPersonReceivingEvidence, new { @placeholder = "Person who received the evidence", @type = "text", @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">Department Received<span class="text-danger">*</span></label>
                        <div class="col-sm-8 col-form-box">
                           
                            @Html.TextBoxFor(m => m.OrganizationReceivingEvidence, new { @placeholder = "Department that received the evidence", @type = "text", @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">Evidence Sent By<span class="text-danger">*</span></label>
                        <div class="col-sm-8 col-form-box">
                       
                            @Html.TextBoxFor(m => m.MPersonHandingOverEvidence, new { @placeholder = "Person who sent the evidence", @type = "text", @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">@*Department Sent By*@Organization Sent by<span class="text-danger">*</span></label>
                        <div class="col-sm-8 col-form-box">
                         
                            @Html.TextBoxFor(m => m.MOrganizationHandingOverEvidence, new { @placeholder = "Organization that sent the evidence", @type = "text", @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">Custodian Of The Evidence<span class="text-danger">*</span></label>
                        <div class="col-sm-8 col-form-box">

                            @Html.TextBoxFor(m => m.MCustodianOfEvidence, new { @placeholder = "Person who is current custodian", @type = "text", @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">
                            Shipment Mode
                        </label>
                        <div class="col-sm-8 col-form-box">
                            @Html.DropDownListFor(m => m.LKShipmentModeID, ViewBag.Shipment_Selection as SelectList, "Select", new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 col-form-label" for="exampleInputEmail1">Comments</label>
                        <div class="col-sm-8 col-form-box">
                        
                            @Html.TextAreaFor(m => m.ShipmentDetails, new { @placeholder = "Courier agency details and bill number or airway bill number", @type = "text", @class = "form-control", @style = "height: inherit" })
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="modal-footer">
            @if (Convert.ToInt32(Session["roleid"]) == 4 && Convert.ToInt32(TempData["INV_STATUS"]) != 2 || Convert.ToInt32(Session["roleid"]) == 7)
            {
        <button type="button" class="btn btn-save" onclick="SaveMovement()">Save Evidence Movement</button>
            }
       
        </div>
    }
</div>
<script>
    $(document).ready(function () {
        $('.date_only_nofuture').datetimepicker({
            format: 'DD/MM/YYYY',
            maxDate: moment().endOf('d')
        });
        $('#EvidenceReturned').change(function () {
            var n1 = document.getElementById('OrganizationHandingOverEvidence');
            var n2 = document.getElementById('MCustodianOfEvidence');
            if (this.checked) {
                n2.value = n1.value;
            } else {
                n2.value = '';
            }
            $('#EvidenceReturned').val(this.checked);
        });
    });
</script>

ISM_Project/Views/Task/sendexternallink.cshtml
@model ISM_Project.Models.ExternalStake
@{
    ViewBag.Title = "sendexternallink";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string grpname = string.Empty;
    string eventname = string.Empty;
    string extemail = string.Empty;
    int j = 1;
}



<div class="container-fluid">
    <div class="col-md-12">
        <div class="row">
            <div class="main-user-wrapper">
                <div class="x_panel">
                    <div class="x_content">

                        <div class="create-user-table send-x-link">
                            @*repeat*@

                            @foreach (var st in Model.Ext_stk_holder)
                {
                    if (grpname != st.InvestigationTaskGroupName)
                    {
                        grpname = st.InvestigationTaskGroupName;

                        <div class="info-tittle">
                            <h2>@st.InvestigationTaskGroupName</h2>
                        </div>
        }
        if (eventname != st.InvestigationTaskGroupEventUniqueNumber)
        {
            eventname = st.InvestigationTaskGroupEventUniqueNumber;
            <div class="form-group">
                <label class="col-sm-4 col-form-label" for="exampleInputEmail1">@st.InvestigationTaskGroupEventName</label>
                <div class="col-sm-8 col-form-box">@st.ExternalName</div>
            </div>
}



}
                        </div>
                    </div>
                </div>
                @using (Html.BeginForm(null, null, FormMethod.Post, new { id = "Save_extdetails" }))
                {
            <div class="x_panel">
                <div class="info-tittle">
                    <h2>External Holder Details</h2>
                </div>
                <div class="create-user-table send-link-notification">
                    @*repeat*@
                    @foreach (var ext_email in Model.Ext_stk_holder_email)
                    {

                        if (extemail != ext_email.ExternalHolderName)
                        {

                            extemail = ext_email.ExternalHolderName;
                    <div class="info-tittle">
                        <h2>
                            @ext_email.ExternalHolderName
                                           
                            @Html.Hidden("holdername[]", Model.OperatorName, new { id = "holdername_" + j})
                                            </h2>
                    </div>
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="col-sm-12 col-form-label" for="exampleInputEmail1">First Name<span class="text-danger"></span></label>
                                <div class="col-sm-12 col-form-box">
                                 
                                    @Html.TextBox("FirstName[]", Model.FirstName_, new { id = "FirstName_" + j, @class = "form-control" })
                                    <small id="emailHelp" class="form-text text-muted"></small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="col-sm-12 col-form-label" for="exampleInputEmail1">Last Name<span class="text-danger"></span></label>
                                <div class="col-sm-12 col-form-box">
                               
                                    @Html.TextBox("LastName[]", Model.FirstName_, new { id = "LastName_" + j, @class = "form-control" })
                                    <small id="emailHelp" class="form-text text-muted"></small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="col-sm-12 col-form-label" for="exampleInputEmail1">Email ID<span class="text-danger"></span></label>
                                <div class="col-sm-12 col-form-box">
                    
                                    @Html.TextBox("Email[]", Model.Email_id, new { id = "Email_" + j, @class = "form-control" })
                                    <small id="emailHelp" class="form-text text-muted"></small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                            j++;
                        }
                    }
                    
                </div>
            </div>
                <div class="inver-btns">

                    <button type="submit" class="btn btn-notify" id="BtnExternal">Save</button>

                </div>
                }
            </div>
        </div>
    </div>