ISM_Project/Models/SR.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ISM_Project.Models
{
    public class SR
    {
        public IEnumerable<USP_VIEW_SR_Result> SRInfo { get; set; }
        public IEnumerable<USP_VIEW_SR_UPDT_HISTORY_Result> SRHIST { get; set; }
        public IEnumerable <USP_VIEW_SR_HISTORIES_Result> SRCOMMU { get; set; }
        public IEnumerable<USP_VIEW_ALL_SR_Result> AllSR { get; set; }
        public IEnumerable<USP_VIEW_INVESTIGATION_FORM35_Result> Inv { get; set; }
        public IEnumerable<USP_VIEW_INVESTIGATION_AIRCRAFT_DETAIL_FORM35_Result> Inv_AircraftDet { get; set; }
        public IEnumerable<USP_SR_ATTACHMENTS_Result> SR_Attach { get; set; }
        public IEnumerable<USP_VIEW_LATEST_SR_STATUS_Result> SR_Status { get; set; }
        public string SafetyRecommendationNumber { get; set; }
        [AllowHtml]
        public string SafetyRecommendation { get; set; }
        public int InvestigationFileID { get; set; }
        public System.DateTime SafetyRecommendationDateCreated { get; set; }
        public string FirstName { get; set; }
        public string FirstName1 { get; set; }
        public System.DateTime DateChanged { get; set; }
        public string ReasonForUpdate { get; set; }
        public string DAAIFeedback { get; set; }
        public string DAAIStatus { get; set; }
        public int SR_ID { get; set; }
        public HttpPostedFileBase[] SRFiles { get; set; }

        public int SRResponseID { get; set; }
        public Nullable<int> SRID { get; set; }
        public string EncodedURL { get; set; }
        public Nullable<bool> StakeholederResponseStatus { get; set; }
        public string StakeholederEmailID { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string SRCommandAction { get; set; } 

        public int SRHistoryID { get; set; }
        public string StakeholderResponse { get; set; }
        public string IICCommentsforSHResponse { get; set; }
        public int IICImplementationStatus { get; set; }
        public string SRCommitteeComments { get; set; }
        public string SRCommitteeClosureStatus { get; set; }
        public string IICClosureComments { get; set; }
        public int SRStatus { get; set; }

        public int SRCommitteeRandomLinkID { get; set; }
        public Nullable<bool> SRCommitteeActionStatus { get; set; }
        public string SRCommitteeEmailID { get; set; }
        public Nullable<int> IICImplementaionStatus { get; set; }
        public string SRIMPLEMENTATIONSTATUS { get; set; }
        public string HistoryOfFlight { get; set; }

        public int CorresRecipientID { get; set; }

        public int TypeofsafetyRecommendation { get; set; }
        public int safetyRecommendationyear { get; set; }

        public IEnumerable<USP_VIEW_ALL_SR_FORDELETE_Result> SR_info { get; set; }

        public string SafetyRecommendationAssignedTo { get; set; }
    }
}

ISM_Project/Controllers/SRController.cs
using ISM_Project.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ISM_Project.Controllers
{
    /// <summary>
    /// SR - Controller contains various process of the investigation safety recommendation work flow and print SR details as PDF
    /// </summary> 
    /// 
    public class SRController : Controller
    {
        Common comm = new Common();
        MailConfiguration mail = new MailConfiguration();
        gcaa_ismEntities db = new gcaa_ismEntities();
        PdfGeneration pdf = new PdfGeneration();
        static string[] SharepointfilePath = new string[100];
        static string[] SharepointAnonymousPath = new string[100];
        static int[] DocumentTypeId = new int[100];
        static int InvFileId = 0;
        
        /// <summary>
        /// Create new  safety recommendation the following action method will perform
        /// </summary> 
        /// 
        /// <param name="id">Receive the investigation file id of the particular investigation</param>
        /// <param name="SRid">Receive the safety recommendation id  if already exist.</param>
        public ActionResult AddSR(int id = 0, int SRid = 0)
        {
            var newSR = new SR();
            try
            {
                if (Convert.ToInt32(Session["RoleId"]) == 4 || Convert.ToInt32(Session["RoleId"]) == 7)
                {
                    if (id > 0)
                    {
                        newSR = new SR
                        {
                            Inv = db.USP_VIEW_INVESTIGATION_FORM35(id).ToList(),
                            Inv_AircraftDet = db.USP_VIEW_INVESTIGATION_AIRCRAFT_DETAIL_FORM35(id).ToList(),
                        };
                    }

                    InvFileId = id;
                    var InvInfo = db.USP_VIEW_INVESTIGATION_FORM35(id).FirstOrDefault();
                    string filenum = InvInfo.InvestigationNumber.Split('/')[1];
                    string SRNumber = getSRNumber(id, 2069, DateTime.Now.Year); // set default SR type from Lookup table.
                    //var SR_NUM = db.USP_SR_NUMBER(id, Convert.ToInt32(filenum)).FirstOrDefault();
                    //TempData["SR_NUM"] = SR_NUM.CONTROL_NUM;
                    TempData["SR_NUM"] = SRNumber;
                    TempData["PageHead"] = InvInfo.InvestigationNumber;
                    TempData["BackPage"] = "sr_mg";
                    TempData["active_url_SR_View"] = "tm";
                    TempData["active_url_SR_View_iic"] = "iic";
                    TempData["lf_menu"] = "1";
                    TempData["InvId"] = InvInfo.InvestigationFileID;
                    TempData["InvFileID"] = InvInfo.InvestigationFileID;
                    Session["InvNum"] = InvInfo.InvestigationNumber;

                    var TypeOfSafetyRecomm = db.LKCOMMONs.Where(a => a.LKCOMMONID == 23).ToList().OrderBy(x => x.ID); // from common lookup table
                    SelectList Safety_Recomm = new SelectList(TypeOfSafetyRecomm, "ID", "LKVALUE");
                    ViewBag.TypeOf_SafetyRecomm = Safety_Recomm;

                    ViewBag.SR_Date = DateTime.Now.Year.ToString();
                }
                else
                {
                    return RedirectToAction("Dashboard", "Home");
                }
            }
            catch (System.Exception ex)
            {
                comm.Exception_Log("SRController", "AddSR", "Message : " + ex.Message + "InnerException : " + ex.InnerException + " Line No : " + ex.StackTrace, Convert.ToInt32(Session["UserID"]));

                return RedirectToAction("PageNotFound", "Error");
            }
            //ViewBag.mode = mode;
            return View(newSR);
        }
        /// <summary>
        /// Get maximum number of safety recommendation based on investigation - "Now this method not used because of manual SR No"
        /// </summary> 
        /// 
        /// <param name="id">Receive the investigation file id</param>
        /// <param name="srtype">Receive the type of safety recommendation</param>
        /// <param name="sryear">Year of safety recommendation year</param>
        public string getSRNumber(int id, int srtype, int sryear)
        {
            if (sryear <= 0)
            {
                sryear = DateTime.Now.Year;
            }

            string SR_NUM = string.Empty;
            //var SRDet = db.USP_GET_PRE_SR_NUMBER(id, srtype).FirstOrDefault();
            //var InvDet = db.InvestigationFiles.Where(a => a.InvestigationFileID == id).Select(a => a.InvestigationFileNumber).FirstOrDefault();

            //if (srtype == 2069) // Prompt Safety Recommendation - from common lookup table
            //{
            //    if (SRDet != null)
            //    {
            //        if (SRDet.MAXSRNUM >= 1)
            //        {
            //            //SRNum = SRNum.Split('/')[3].Split('-')[0].Split('R')[1];
            //            int newSRNo = Convert.ToInt32(SRDet.MAXSRNUM) + 1;
            //            if (newSRNo < 10)
            //                SR_NUM = InvDet + "/" + "PSR" + "0" + newSRNo + "-" + sryear;
            //            else
            //                SR_NUM = InvDet + "/" + "PSR" + newSRNo + "-" + sryear;
            //        }
            //    }
            //    else
            //    {
            //        SR_NUM = InvDet + "/" + "PSR" + "01" + "-" + sryear;
            //    }
            //}
            //else if (srtype == 2070) // Safety Recommendation - from common lookup table
            //{
            //    if (SRDet != null)
            //    {
            //        if (SRDet.MAXSRNUM >= 1)
            //        {
            //            int newSRNo = Convert.ToInt32(SRDet.MAXSRNUM) + 1;
            //            if (newSRNo < 10)
            //                SR_NUM = InvDet + "/" + "SR" + "0" + newSRNo + "-" + sryear;
            //            else
            //                SR_NUM = InvDet + "/" + "SR" + newSRNo + "-" + sryear;
            //        }
            //    }
            //    else
            //    {
            //        SR_NUM = InvDet + "/" + "SR" + "01" + "-" + sryear;
            //    }
            //}
            //else if (srtype == 2071) // Foreign Safety Recommendation - from common lookup table
            //{
            //    if (SRDet != null)
            //    {
            //        if (SRDet.MAXSRNUM >= 1)
            //        {
            //            int newSRNo = Convert.ToInt32(SRDet.MAXSRNUM) + 1;
            //            if (newSRNo < 10)
            //                SR_NUM = InvDet + "/" + "FSR" + "0" + newSRNo + "-" + sryear;
            //            else
            //                SR_NUM = InvDet + "/" + "FSR" + newSRNo + "-" + sryear;
            //        }
            //    }
            //    else
            //    {
            //        SR_NUM = InvDet + "/" + "FSR" + "01" + "-" + sryear;
            //    }
            //}

            return SR_NUM;
        }
        /// <summary>
        /// Save the new safety recommendation to database based on the investigation file number
        /// </summary> 
        /// 
        /// <param name="NewSR">Receive the safety recommendation details as object </param>
        [HttpPost]
        public ActionResult AddSR(SR NewSR)
        {
            try
            {               
                saveFilestoSharePoint(Request.Files, NewSR.SafetyRecommendationNumber); // save the attached safety recommendation files to sharepoint
                string siteURL = string.Format("{0}://{1}{2}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"));
                if (Convert.ToInt32(Session["RoleId"]) == 4 || Convert.ToInt32(Session["RoleId"]) == 7)
                {
                    int msgID = 0;
                    if (Convert.ToInt32(Session["UserID"]) > 0)
                    {
                        var checkSRNumber = db.InvestigationSafetyRecommendations.Where(a => a.SafetyRecommendationNumber == NewSR.SafetyRecommendationNumber
                        
                                              && a.InvestigationFileID == NewSR.InvestigationFileID)

                                              .Select(b => b.SafetyRecommendationNumber).FirstOrDefault();

                        if (checkSRNumber == null)
                        {
                            //getSRNumber(NewSR.InvestigationFileID, NewSR.TypeofsafetyRecommendation, NewSR.safetyRecommendationyear)
                            var msg = db.USP_INST_SR("INSERT",NewSR.SafetyRecommendationNumber, NewSR.SafetyRecommendation, Convert.ToInt32(Session["UserId"]), NewSR.InvestigationFileID, "Pending", 0, null, NewSR.TypeofsafetyRecommendation,NewSR.SafetyRecommendationAssignedTo).FirstOrDefault();
                            msgID = Convert.ToInt32(msg.SRID);
                            for (int i = 0; i < SharepointfilePath.Length; i++)
                            {
                                if (SharepointfilePath[i] != null)
                                    db.USP_SR_ATTACHMENTS("insert", Convert.ToInt32(msgID), 0, DocumentTypeId[i], SharepointfilePath[i], SharepointAnonymousPath[i], Convert.ToInt32(Session["UserId"]));
                                else
                                    break;
                            }
                            // commented since mail notification to DAAI is not required now.
                            //var DList = db.Users.AsQueryable().Where(d => d.UserID == 3).Select(x => new { x.EmailAddress, x.FirstName }).FirstOrDefault();
                            //List<string> DListUsers = new List<string>();
                            //List<string> DListUsersEmail = new List<string>();
                            //DListUsersEmail.Add(DList.EmailAddress);

ISM_Project/Views/SR/SR_View.cshtml
@{
    ViewBag.Title = "SR_View";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/js/Common.js"></script>

<div class="main_ism_wrapper">
    <div class="container-fluid">
        <div class="col-md-12">
            <div class="row">
                <div class="main-user-wrapper investigation-scope-wrapper">
                 
                    <div class="main-wrapper">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="row">
                                <div class="x_panel">
                                    <div class="x_content form-create-user-table">
                                        <div class="info-tittle">
                                            <h2>Safety Recommendations</h2>
                                        </div>
                                        <form>
                                            <div class="scope-details">
                                                <div class="row">
                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label class="col-sm-6 col-form-label" for="exampleInputEmail1">
                                                                AAI Case ID:
                                                            </label>
                                                            <div class="col-sm-6 col-form-box">
                                                                <label class="form-values">AIFN/0001/2018</label>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="col-sm-6 col-form-label" for="exampleInputEmail1">
                                                                UTC Date & Time of Occurrence:
                                                            </label>
                                                            <div class="col-sm-6 col-form-box">
                                                                <label class="form-values">27-01-2017 09:45</label>
                                                            </div>
                                                        </div>
                                                     
                                                    </div>

                                                    <div class="col-md-6">
                                                        <div class="form-group">
                                                            <label class="col-sm-6 col-form-label" for="exampleInputEmail1">
                                                                Investigator In-Charge:
                                                            </label>
                                                            <div class="col-sm-6 col-form-box">
                                                                <label class="form-values">Yusuf Khan</label>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <label class="col-sm-6 col-form-label" for="exampleInputEmail1">
                                                                Local Date & Time of Occurrence:
                                                            </label>
                                                            <div class="col-sm-6 col-form-box">
                                                                <label class="form-values">27-01-2017 09:45</label>
                                                            </div>
                                                        </div>
                                                     
                                                    </div>
                                                </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                                <div class="clearfix"></div>
                                <div class="x_panel">
                                    <div class="x_content form-create-user-table">
                                        <div class="info-tittle">
                                            <h2>SR List</h2> @*Safety Recommendations List*@
                                        </div>
                                        <div class="task-scope-wrapp saftey-tape">
                                            <div class="search-field">
                                                <div class="i-search nc">
                                                    <div id="custom-search-input">
                                                        <div class="input-group">
                                                            <input type="text" class="form-control" placeholder="Search" />
                                                            <span class="input-group-btn">
                                                                <button class="btn btn-info btn-lg" type="button">
                                                                    <i class="fa fa-search" aria-hidden="true"></i>
                                                                </button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="occ-new">
                                                    <button type="button" class="btn btn-addnew" onclick="location.href='@Url.Action("New_SR", "SR",new { mode="new"})'">
                                                        <i class="fas fa-plus"></i>Add New
                                                    </button>
                                                </div>
                                            </div>
                                            <div class="main-wrapper current-project-wrapper">
                                                <div class="col-md-12 col-sm-12 col-xs-12">
                                                    <div class="row">
                                                        <div class="x_panel-corres">
                                                            <div class="x_content">
                                                                <div class="table-tittle">

                                                                </div>
                                                                <div class="table-responsive">
                                                                    <table id="datatable" class="table table-responsive table-bordered table-hover correspondance-table">
                                                                        <!-- need pagination table -->
                                                                        <thead>
                                                                            <tr>
                                                                            
                                                                                <th>SR ID Number</th>
                                                                                <th>Date Created</th>
                                                                                <th>Status</th>


                                                                            </tr>
                                                                        </thead>
                                                                        <tbody>
                                                                            <tr>
                                                                        
                                                                                <td> @Html.ActionLink("SRNA22/2018/11", "New_SR", "SR", routeValues: new { mode = "view" }, htmlAttributes: null)</td>
                                                                                <td>12/06/2018</td>
                                                                                <td>Pending</td>


                                                                            </tr>
                                                                            <tr>
                                                                          
                                                                                <td> @Html.ActionLink("SRNA13/2018/11", "New_SR", "SR", new { mode = "view" }, htmlAttributes: null)</td>
                                                                                <td>14/06/2018</td>
                                                                                <td>Not Approved</td>


                                                                            </tr>
                                                                            <tr>
                                                                              
                                                                                <td> @Html.ActionLink("SRNA08/2018/11", "New_SR", new { mode = "view" }, htmlAttributes: null)</td>
                                                                                <td>12/06/2018</td>
                                                                                <td>Not Approved</td>


                                                                            </tr>
                                                                            <tr>
                                                                           
                                                                                <td> @Html.ActionLink("SRNA05/2018/11", "New_SR", "SR", new { mode = "view" }, htmlAttributes: null)</td>
                                                                                <td>14/06/2018</td>
                                                                                <td>DAAI Approved</td>


                                                                            </tr>
                                                                            <tr>
                                                                             
                                                                                <td> @Html.ActionLink("SRNA02/2018/11", "New_SR", "SR", new { id = 1 }, htmlAttributes: null)</td>
                                                                                <td>19/06/2018</td>
                                                                                <td>DAAI Approved</td>

                                                                            </tr>
                                                                        </tbody>
                                                                    </table>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>


                                        </div>
                                    </div>
                                </div>


                            </div>
                            <!-- sumitted form btns -->
                            <!-- sumitted form btns -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>